# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Thw"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: haowen_t@163.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: '春风'
author: '春风'
# author_image: "/assets/images/author.jpg"

paginate:	5

# url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/thwzjx
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
